USE [IAMDB];
GO
/* =========================
 FKs (sin cascada)
 ========================= */

-- TBL_TARIFAS -> NEGOCIOS
IF NOT EXISTS (
    SELECT 1
    FROM sys.foreign_keys
    WHERE [name] = 'FK_TBL_TARIFAS_NEGOCIOS'
) BEGIN
ALTER TABLE CORE.TBL_TARIFAS
ADD CONSTRAINT FK_TBL_TARIFAS_NEGOCIOS FOREIGN KEY (ID_Negocio) REFERENCES CORE.TBL_NEGOCIOS (ID_Negocio) ON UPDATE NO ACTION ON DELETE NO ACTION;
END
GO -- TBL_TARIFAS -> ESTADOS
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE [name] = 'FK_TBL_TARIFAS_ESTADOS'
    ) BEGIN
ALTER TABLE CORE.TBL_TARIFAS
ADD CONSTRAINT FK_TBL_TARIFAS_ESTADOS FOREIGN KEY (ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado) ON UPDATE NO ACTION ON DELETE NO ACTION;
END
GO -- TBL_PROFORMAS -> NEGOCIOS
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE [name] = 'FK_TBL_PROFORMAS_NEGOCIOS'
    ) BEGIN
ALTER TABLE CORE.TBL_PROFORMAS
ADD CONSTRAINT FK_TBL_PROFORMAS_NEGOCIOS FOREIGN KEY (ID_Negocio) REFERENCES CORE.TBL_NEGOCIOS (ID_Negocio) ON UPDATE NO ACTION ON DELETE NO ACTION;
END
GO -- TBL_PROFORMAS -> CLIENTES (permite NULL)
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE [name] = 'FK_TBL_PROFORMAS_CLIENTES'
    ) BEGIN
ALTER TABLE CORE.TBL_PROFORMAS
ADD CONSTRAINT FK_TBL_PROFORMAS_CLIENTES FOREIGN KEY (ID_Cliente) REFERENCES CORE.TBL_CLIENTES (ID_Cliente) ON UPDATE NO ACTION ON DELETE NO ACTION;
END
GO -- TBL_PROFORMAS -> ESTADOS
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE [name] = 'FK_TBL_PROFORMAS_ESTADOS'
    ) BEGIN
ALTER TABLE CORE.TBL_PROFORMAS
ADD CONSTRAINT FK_TBL_PROFORMAS_ESTADOS FOREIGN KEY (ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado) ON UPDATE NO ACTION ON DELETE NO ACTION;
END
GO -- TBL_PROFORMAS_ITEMS -> PROFORMAS
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE [name] = 'FK_TBL_PROFORMAS_ITEMS_PROFORMAS'
    ) BEGIN
ALTER TABLE CORE.TBL_PROFORMAS_ITEMS
ADD CONSTRAINT FK_TBL_PROFORMAS_ITEMS_PROFORMAS FOREIGN KEY (ID_Proforma) REFERENCES CORE.TBL_PROFORMAS (ID_Proforma) ON UPDATE NO ACTION ON DELETE NO ACTION;
END
GO -- TBL_PROFORMAS_ITEMS -> ESTADOS
    IF NOT EXISTS (
        SELECT 1
        FROM sys.foreign_keys
        WHERE [name] = 'FK_TBL_PROFORMAS_ITEMS_ESTADOS'
    ) BEGIN
ALTER TABLE CORE.TBL_PROFORMAS_ITEMS
ADD CONSTRAINT FK_TBL_PROFORMAS_ITEMS_ESTADOS FOREIGN KEY (ID_Estado) REFERENCES UTIL.TBL_ESTADOS (ID_Estado) ON UPDATE NO ACTION ON DELETE NO ACTION;
END
GO